language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install gevent argparse pytest-cov coveralls"
# command to run tests
script: py.test --cov factory tests/
# grab info for https://coveralls.io/
after_success: coveralls
